# Generated by Django 4.2 on 2025-07-15 04:56

from django.db import migrations
import users.manages


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', users.manages.MyUserManager()),
            ],
        ),
    ]
